apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  labels:
    app: postgresql
data:
  database-name: cG9zdGdyZXM=
  database-password: c3NvMTIzNA==
  database-user: a2V5Y2xvYWs=
type: Opaque
