apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  labels:
    app: keycloak
  namespace: rhbk
spec:
  http:
    tlsSecret: my-tls-dev-cert
  hostname:
    hostname: keycloak.apps.home.myocp.net
  db:
    usernameSecret:
      key: database-user
      name: postgresql
    passwordSecret:
      name: postgresql
      key: database-password
    port: 5432
    vendor: postgres
    host: postgres
    url: jdbc:postgresql://postgresql:5432/postgres
    database: postgres
  instances: 1
