apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  instances: 1
  hostname: 
     hostname: keycloak.apps.home.myocp.net
  tlsSecret: my-tls-dev-cert
  image: quay.io/msauve/keycloak-custom:latest
  serverConfiguration:
    - name: features
      value: web-authn,openshift-integration
    - name: db
      value: postgres
    - name: db-password
      value: sso1234
    - name: db-url
      value: jdbc:postgresql://postgresql:5432/keycloak
    - name: db-username
      value: keycloak
    - name: cache
      value: ispn