kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: keycloak-infra-project
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  orphanedResources:
    warn: true
  sourceRepos:
    - '*'

