apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-tls-secret
  namespace: keycloak-quarkus
spec:
  secretName: my-tls-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - keycloak.apps.home.myocp.net
